export const projectsData = [
  {
    id: 1,
    image: '/projects/01.png',
    category: 'Front-end',
    title: 'Figma to react/nextjs',
    description:
      'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested'
  },
  {
    id: 2,
    image: '/projects/02.png',
    category: 'Full-stack',
    title: ' Github API',
    description:
      'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested'
  },
  {
    id: 3,
    image: '/projects/03.png',
    category: 'Full-stack',
    title: ' Graphql By example',
    description:
      'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested'
  }
]

export const askedQuestions = [
  {
    id: 1,
    qs: 'can you work on my project immediately?',
    answer:
      'Yes, if i am not currently engaged in other commitments, otherwise i will get the jobe done in deadline'
  },
  {
    id: 2,
    qs: 'are you working hourly base or by projects ?',
    answer: 'both of them it&apos; depends on client choice'
  },
  {
    id: 3,
    qs: 'What are technologies you use in your stack?',
    answer: 'i am using latest in cutting edge technology conerning MERN Stack'
  }
]


export const italianUniversities = [
  {
    "id": 1,
    "name": "Politecnico di Milano",
    "tutorial": null,
    "blog": "Blog on Polimi",
    "admission_fee": 50,
    "english_requirement": "English Proficiency",
    "admission_date": "Oct 1, 2024",
    "deadline": "2 Dec",
    "status": "Close",
    "cgpa_requirement": "MINIMUM CGPA 3.3 FOR PAKISTAN"
  },
  {
    "id": 2,
    "name": "University of Padua (First Call)",
    "tutorial": null,
    "blog": "Blog on UniPd",
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 2, 2024",
    "deadline": "2 Feb",
    "status": "Open",
    "cgpa_requirement": "MINIMUM CGPA 3.1 FOR PAKISTAN"
  },
  {
    "id": 3,
    "name": "University of Macerata",
    "tutorial": null,
    "blog": "Blog on UniMc",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 4, 2024",
    "deadline": "31 Mar",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 4,
    "name": "University of Milano-Bicocca",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 5, 2024",
    "deadline": "10 Feb",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 5,
    "name": "University of Bergamo (First Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 7, 2024",
    "deadline": "15 Jan",
    "status": "Close",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 6,
    "name": "University of Pavia",
    "tutorial": "YouTube Video",
    "blog": "Blog on UNiPv",
    "admission_fee": 35,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 13, 2024",
    "deadline": "21 Nov",
    "status": "Close",
    "cgpa_requirement": "MINIMUM 2.65 CGPA REQUIRED"
  },
  {
    "id": 7,
    "name": "University of Genoa",
    "tutorial": "YouTube Video",
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 18, 2024",
    "deadline": "14 Mar",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 8,
    "name": "University of Camerino",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 20, 2024",
    "deadline": "30 Mar",
    "status": "Open",
    "cgpa_requirement": "MINIMUM CGPA 3 FOR PAKISTAN"
  },
  {
    "id": 9,
    "name": "University of Turin",
    "tutorial": null,
    "blog": null,
    "admission_fee": 60,
    "english_requirement": "Different for each program / English Proficiency / IELTS",
    "admission_date": "Nov 26, 2024",
    "deadline": "30 Jan",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 10,
    "name": "University of Bologna",
    "tutorial": "YouTube Video",
    "blog": null,
    "admission_fee": "Variable (0/20/50)",
    "english_requirement": "Different for each program / English Proficiency / IELTS",
    "admission_date": "Nov 28, 2024",
    "deadline": "Different for each program",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 11,
    "name": "University of Florence",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 2, 2024",
    "deadline": "21 Feb",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 12,
    "name": "Politecnico di Milano 2nd Call (Architecture and Design)",
    "tutorial": null,
    "blog": "Blog on Polimi",
    "admission_fee": 150,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 3, 2024",
    "deadline": "30 Jan",
    "status": "Open",
    "cgpa_requirement": "MINIMUM CGPA 3.3 FOR PAKISTAN"
  },
  {
    "id": 13,
    "name": "Sapienza University of Rome",
    "tutorial": null,
    "blog": "Blog on UniRome1",
    "admission_fee": 30,
    "english_requirement": "IELTS Required",
    "admission_date": "Dec 5, 2024",
    "deadline": "29 Apr",
    "status": "Open",
    "cgpa_requirement": "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 14,
    "name": "University of L'Aquila",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 8, 2025",
    "deadline": "5 Mar",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 15,
    "name": "University of Pisa",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "12 Dec, 2025",
    "deadline": "Different for each program",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 16,
    "name": "Marche Polytechnic University",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 16, 2024",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 17,
    "name": "University of Trento",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 18, 2024",
    "deadline": "6 Mar",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 18,
    "name": "Ca' Foscari University of Venice",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 19, 2024",
    "deadline": "9 Jan",
    "status": "Close",
    "cgpa_requirement": "MINIMUM 2.8 CGPA REQUIRED"
  },
  {
    "id": 19,
    "name": "Polytechnic University of Turin",
    "tutorial": null,
    "blog": null,
    "admission_fee": 50,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 19, 2024",
    "deadline": "1Feb",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 20,
    "name": "University of Bergamo (Second Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 1, 2025",
    "deadline": "31 Jan",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 21,
    "name": "University of Siena",
    "tutorial": null,
    "blog": null,
    "admission_fee": 40,
    "english_requirement": "IELTS Required",
    "admission_date": "1 Jan, 2025",
    "deadline": "6 Feb , 6 May",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 22,
    "name": "University of Tuscia",
    "tutorial": null,
    "blog": "Blog on Tuscia",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "1 Jan, 2025",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 23,
    "name": "University of Parma",
    "tutorial": null,
    "blog": "Communication Engineering",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "10 Dec, 2025",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 24,
    "name": "University of Padua (Limited Programs)",
    "tutorial": null,
    "blog": "Blog on UniPd",
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 7, 2025",
    "deadline": "7 Mar",
    "status": "Open",
    "cgpa_requirement": "MINIMUM CGPA 3.1 FOR PAKISTAN"
  },
  {
    "id": 25,
    "name": "University of Pavia (2nd Call)",
    "tutorial": "YouTube Video",
    "blog": "Blog on UniPv",
    "admission_fee": 35,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 9, 2025",
    "deadline": "16 Jan",
    "status": "Close",
    "cgpa_requirement": "MINIMUM 2.65 CGPA REQUIRED"
  },
  {
    "id": 26,
    "name": "University of Trieste",
    "notes": "Not accepting application from: Ethiopia, Iran, Pakistan",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 7, 2025",
    "deadline": "7 Feb",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 27,
    "name": "University of Milano-Bicocca (Limited)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 7, 2025",
    "deadline": "7 Mar",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 28,
    "name": "Politecnico di Milano (Engineering)",
    "tutorial": null,
    "blog": "Blog on Polimi",
    "admission_fee": 150,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 13, 2025",
    "deadline": "27 Feb",
    "status": "Open",
    "cgpa_requirement": "MINIMUM CGPA 3.3 FOR PAKISTAN"
  },
  {
    "id": 29,
    "name": "University of Insubria",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "15 Jan, 2025",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": null
  },
  {
    "id": 30,
    "name": "University of Tor Vergata",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 21, 2025",
    "deadline": "31 May",
    "status": "Open",
    "cgpa_requirement": "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 31,
    "name": "University of Milan",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 1, 2025",
    "deadline": "31 Mar",
    "status": null,
    "cgpa_requirement": "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 32,
    "name": "University of Parma",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 1, 2025",
    "deadline": "1 Mar",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 33,
    "name": "University of Messina",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "IELTS Required",
    "admission_date": "Feb 1, 2025",
    "deadline": "21 Feb",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 34,
    "name": "University of Catania",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 2, 2025",
    "deadline": "15 Mar",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 35,
    "name": "University of Sassari",
    "tutorial": null,
    "blog": "Innovation management for sustainable tourism",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 10, 2025",
    "deadline": "30 Mar",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 36,
    "name": "University of Modena",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 30, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 37,
    "name": "University of Cassino",
    "tutorial": null,
    "blog": "Blog on UniCas",
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 13, 2025",
    "deadline": "30 Apr",
    "status": null,
    "cgpa_requirement": "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 38,
    "name": "University of Tuscia",
    "tutorial": null,
    "blog": "Blog on UniTs",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 13, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 39,
    "name": "University of Milano-Bicocca (Second)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 17, 2025",
    "deadline": "2 May",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 40,
    "name": "University of Turin (Bachelor)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "Different for each program",
    "admission_date": "Feb 24, 2025",
    "deadline": "30 Apr",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 41,
    "name": "Polytechnic University of Turin (2nd)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 50,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 1, 2025",
    "deadline": "4 Apr",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 42,
    "name": "University of Bozen-Bolzano",
    "tutorial": null,
    "blog": null,
    "admission_fee": 50,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 1, 2025",
    "deadline": "7 May",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 43,
    "name": "University of Verona",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 1, 2025",
    "deadline": "30 Mar",
    "status": null,
    "cgpa_requirement": "MINIMUM 3 CGPA REQUIRED"
  },
  {
    "id": 44,
    "name": "University of Padua (Second Call)",
    "tutorial": null,
    "blog": "Blog on UniPd",
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 2, 2025",
    "deadline": "2 May",
    "status": null,
    "cgpa_requirement": "MINIMUM CGPA 3.1 FOR PAKISTAN"
  },
  {
    "id": 45,
    "name": "University of Calabria",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 4, 2025",
    "deadline": "10 Apr",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 46,
    "name": "University of Pavia (3rd Call)",
    "tutorial": "YouTube Video",
    "blog": "Blog on UniPv",
    "admission_fee": 35,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 10, 2025",
    "deadline": "18 Mar",
    "status": null,
    "cgpa_requirement": "MINIMUM 2.65 CGPA REQUIRED"
  },
  {
    "id": 47,
    "name": "University of Florence (Second Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 18, 2025",
    "deadline": "17 May",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 48,
    "name": "University of Messina (Second Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "IELTS Required",
    "admission_date": "Mar 22, 2025",
    "deadline": "3 May",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 49,
    "name": "Polytechnic University of Bari",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 50,
    "name": "Roma Tre University",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 51,
    "name": "University of Bari Aldo Moro",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 52,
    "name": "University of Basilicata",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 53,
    "name": "University of Campania Luigi Vanvitelli",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 54,
    "name": "University of Eastern Piedmont",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": "30 Aug",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 55,
    "name": "University of Ferrara",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 15, 2025",
    "deadline": "30 Apr",
    "status": "Open",
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 56,
    "name": "University of Foggia",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 57,
    "name": "University of Naples Federico II",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 58,
    "name": "University of Naples Parthenope",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 59,
    "name": "University of Palermo",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 60,
    "name": "University of Perugia",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 61,
    "name": "University of Salento",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 62,
    "name": "University of Salerno",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 63,
    "name": "University of Teramo",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 64,
    "name": "University of Cagliari",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "IELTS/TOLC Required",
    "admission_date": "Apr 1, 2025",
    "deadline": "9 Jun",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  },
  {
    "id": 65,
    "name": "University of Udine",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "May 9, 2025",
    "deadline": "15 Jun",
    "status": null,
    "cgpa_requirement": "NO CGPA REQUIREMENT"
  }
]