export const projectsData = [
  {
    id: 1,
    image: '/projects/01.png',
    category: 'Front-end',
    title: 'Figma to react/nextjs',
    description:
      'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested'
  },
  {
    id: 2,
    image: '/projects/02.png',
    category: 'Full-stack',
    title: ' Github API',
    description:
      'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested'
  },
  {
    id: 3,
    image: '/projects/03.png',
    category: 'Full-stack',
    title: ' Graphql By example',
    description:
      'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested'
  }
]

export const askedQuestions = [
  {
    id: 1,
    qs: 'can you work on my project immediately?',
    answer:
      'Yes, if i am not currently engaged in other commitments, otherwise i will get the jobe done in deadline'
  },
  {
    id: 2,
    qs: 'are you working hourly base or by projects ?',
    answer: 'both of them it&apos; depends on client choice'
  },
  {
    id: 3,
    qs: 'What are technologies you use in your stack?',
    answer: 'i am using latest in cutting edge technology conerning MERN Stack'
  }
]


export const italianUniversities = [
  {
    "id": 51,
    "name": "Univ. of Bari Aldo Moro",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 52,
    "name": "Univ. of Basilicata",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 5,
    "name": "Univ. of Bergamo (First Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 7, 2024",
    "deadline": "15 Jan",
    "status": "Close",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 20,
    "name": "Univ. of Bergamo (Second Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 1, 2025",
    "deadline": "31 Jan",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 42,
    "name": "Univ. of Bozen-Bolzano",
    "tutorial": null,
    "blog": null,
    "admission_fee": 50,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 1, 2025",
    "deadline": "7 May",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 64,
    "name": "Univ. of Cagliari",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "IELTS/TOLC Required",
    "admission_date": "Apr 1, 2025",
    "deadline": "9 Jun",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 45,
    "name": "Univ. of Calabria",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 4, 2025",
    "deadline": "10 Apr",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 8,
    "name": "Univ. of Camerino",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 20, 2024",
    "deadline": "30 Mar",
    "status": "Open",
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min CGPA 3"
  },
  {
    "id": 53,
    "name": "Univ. of Campania Luigi Vanvitelli",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 37,
    "name": "Univ. of Cassino",
    "tutorial": null,
    "blog": "Blog on UniCas",
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 13, 2025",
    "deadline": "30 Apr",
    "status": null,
    "cgpa_requirement": "Varies by Program" // Old value: "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 34,
    "name": "Univ. of Catania",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 2, 2025",
    "deadline": "15 Mar",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 54,
    "name": "Univ. of Eastern Piedmont",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": "30 Aug",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 55,
    "name": "Univ. of Ferrara",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 15, 2025",
    "deadline": "30 Apr",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 11,
    "name": "Univ. of Florence",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 2, 2024",
    "deadline": "21 Feb",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 47,
    "name": "Univ. of Florence (Second Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 18, 2025",
    "deadline": "17 May",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 56,
    "name": "Univ. of Foggia",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 7,
    "name": "Univ. of Genoa",
    "tutorial": "YouTube Video",
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 18, 2024",
    "deadline": "14 Mar",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 29,
    "name": "Univ. of Insubria",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "15 Jan, 2025",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: null
  },
  {
    "id": 14,
    "name": "Univ. of L'Aquila",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Dec 8, 2025",
    "deadline": "5 Mar",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 3,
    "name": "Univ. of Macerata",
    "tutorial": null,
    "blog": "Blog on UniMc",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 4, 2024",
    "deadline": "31 Mar",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 33,
    "name": "Univ. of Messina",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "IELTS Required",
    "admission_date": "Feb 1, 2025",
    "deadline": "21 Feb",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 48,
    "name": "Univ. of Messina (Second Call)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "IELTS Required",
    "admission_date": "Mar 22, 2025",
    "deadline": "3 May",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 31,
    "name": "Univ. of Milan",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 1, 2025",
    "deadline": "31 Mar",
    "status": null,
    "cgpa_requirement": "Varies by Program" // Old value: "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 4,
    "name": "Univ. of Milano-Bicocca",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 5, 2024",
    "deadline": "10 Feb",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 27,
    "name": "Univ. of Milano-Bicocca (Limited)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 7, 2025",
    "deadline": "7 Mar",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 39,
    "name": "Univ. of Milano-Bicocca (Second)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 17, 2025",
    "deadline": "2 May",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 36,
    "name": "Univ. of Modena",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 30, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "Varies by Program" // Old value: "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 57,
    "name": "Univ. of Naples Federico II",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 58,
    "name": "Univ. of Naples Parthenope",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 2,
    "name": "Univ. of Padua (First Call)",
    "tutorial": null,
    "blog": "Blog on UniPd",
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 2, 2024",
    "deadline": "2 Feb",
    "status": "Open",
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min CGPA 3.1"
  },
  {
    "id": 24,
    "name": "Univ. of Padua (Limited Programs)",
    "tutorial": null,
    "blog": "Blog on UniPd",
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 7, 2025",
    "deadline": "7 Mar",
    "status": "Open",
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min CGPA 3.1"
  },
  {
    "id": 44,
    "name": "Univ. of Padua (Second Call)",
    "tutorial": null,
    "blog": "Blog on UniPd",
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 2, 2025",
    "deadline": "2 May",
    "status": null,
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min CGPA 3.1"
  },
  {
    "id": 59,
    "name": "Univ. of Palermo",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },  {
    "id": 23,
    "name": "Univ. of Parma",
    "tutorial": null,
    "blog": "Communication Engineering",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "10 Dec, 2025",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 32,
    "name": "Univ. of Parma",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 1, 2025",
    "deadline": "1 Mar",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 6,
    "name": "Univ. of Pavia",
    "tutorial": "YouTube Video",
    "blog": "Blog on UNiPv",
    "admission_fee": 35,
    "english_requirement": "English Proficiency",
    "admission_date": "Nov 13, 2024",
    "deadline": "21 Nov",
    "status": "Close",
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min 2.65 CGPA REQUIRED"
  },
  {
    "id": 25,
    "name": "Univ. of Pavia (2nd Call)",
    "tutorial": "YouTube Video",
    "blog": "Blog on UniPv",
    "admission_fee": 35,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 9, 2025",
    "deadline": "16 Jan",
    "status": "Close",
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min 2.65 CGPA REQUIRED"
  },
  {
    "id": 46,
    "name": "Univ. of Pavia (3rd Call)",
    "tutorial": "YouTube Video",
    "blog": "Blog on UniPv",
    "admission_fee": 35,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 10, 2025",
    "deadline": "18 Mar",
    "status": null,
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min 2.65 CGPA REQUIRED"
  },
  {
    "id": 60,
    "name": "Univ. of Perugia",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 15,
    "name": "Univ. of Pisa",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "12 Dec, 2025",
    "deadline": "Different for each program",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 50,
    "name": "Roma Tre Univ.",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 61,
    "name": "Univ. of Salento",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 62,
    "name": "Univ. of Salerno",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 35,
    "name": "Univ. of Sassari",
    "tutorial": null,
    "blog": "Innovation management for sustainable tourism",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 10, 2025",
    "deadline": "30 Mar",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 21,
    "name": "Univ. of Siena",
    "tutorial": null,
    "blog": null,
    "admission_fee": 40,
    "english_requirement": "IELTS Required",
    "admission_date": "1 Jan, 2025",
    "deadline": "6 Feb , 6 May",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 63,
    "name": "Univ. of Teramo",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 31, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 30,
    "name": "Univ. of Tor Vergata",
    "tutorial": null,
    "blog": null,
    "admission_fee": 30,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 21, 2025",
    "deadline": "31 May",
    "status": "Open",
    "cgpa_requirement": "Varies by Program" // Old value: "DIFFERENT CGPA REQUIREMENTS"
  },
  {
    "id": 26,
    "name": "Univ. of Trieste",
    "tutorial": null,
    "blog": null,
    "admission_fee": 10,
    "english_requirement": "English Proficiency",
    "admission_date": "Jan 7, 2025",
    "deadline": "7 Feb",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 9,
    "name": "Univ. of Turin",
    "tutorial": null,
    "blog": null,
    "admission_fee": 60,
    "english_requirement": "Different for each program / English Proficiency / IELTS",
    "admission_date": "Nov 26, 2024",
    "deadline": "30 Jan",
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 40,
    "name": "Univ. of Turin (Bachelor)",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "Different for each program",
    "admission_date": "Feb 24, 2025",
    "deadline": "30 Apr",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 22,
    "name": "Univ. of Tuscia",
    "tutorial": null,
    "blog": "Blog on Tuscia",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "1 Jan, 2025",
    "deadline": null,
    "status": "Open",
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 38,
    "name": "Univ. of Tuscia",
    "tutorial": null,
    "blog": "Blog on UniTs",
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Feb 13, 2025",
    "deadline": null,
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 65,
    "name": "Univ. of Udine",
    "tutorial": null,
    "blog": null,
    "admission_fee": 20,
    "english_requirement": "English Proficiency",
    "admission_date": "May 9, 2025",
    "deadline": "15 Jun",
    "status": null,
    "cgpa_requirement": "not required" // Old value: "NO CGPA REQUIREMENT"
  },
  {
    "id": 43,
    "name": "Univ. of Verona",
    "tutorial": null,
    "blog": null,
    "admission_fee": 0,
    "english_requirement": "English Proficiency",
    "admission_date": "Mar 1, 2025",
    "deadline": "30 Mar",
    "status": null,
    "cgpa_requirement": "Min BAC: 12/20" // Old value: "Min 3 CGPA REQUIRED"
  }
]